# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba358934f795ec88bd19fb482fdb67b2d41a65907e44f3dcedb62c9daeb56a83afb3f726324d2294de97faaf7b982d80dfb031f2174f7d7d77ee2ae9244e7893

test:
  secret_key_base: 0390993adce96851cc04405858f2262410ff078375ceeff7769ad076511e144b4f4178e15e947973f8ac8a871ef9278f0d1b85e1afe44df9b1876576647cb496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
